spring.application.name=DocSphereApi

spring.data.mongodb.uri=${MONGODB_URI}
server.servlet.context-path=/api/v1.0
spring.data.mongodb.auto-index-creation=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

clerk.issuer=${CLERK_ISSUER}
clerk.jwks-url=${CLERK_JWKS_URL}
clerk.webhook.secret=${CLERK_WEBHOOK_SECRET}

#file upload configuration
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=25MB

#razorpay keys
razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}

# Supabase S3 Config
supabase.s3.endpointUrl=${SUPABASE_S3_ENDPOINT_URL}
supabase.s3.accessKey=${SUPABASE_S3_ACCESS_KEY}
supabase.s3.secretKey=${SUPABASE_S3_SECRET_KEY}
supabase.s3.region=${SUPABASE_S3_REGION}
supabase.s3.bucketName=${SUPABASE_S3_BUCKET_NAME}
