spring.application.name=DocSphereApi

spring.data.mongodb.uri=mongodb://localhost:27017/DocSphere
server.servlet.context-path=/api/v1.0
spring.data.mongodb.auto-index-creation=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

clerk.issuer=https://alive-jawfish-15.clerk.accounts.dev
clerk.jwks-url=https://alive-jawfish-15.clerk.accounts.dev/.well-known/jwks.json
clerk.webhook.secret=fzXDnQXB7nLmuyMmDBWA4ndjt9Gxt84d

#file upload configuration
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=25MB

#razorpay keys
razorpay.key.id=rzp_test_SXnVIp1u3lqsCr
razorpay.key.secret=6iSGxMfup3JZcvYBComDQLZD

#cloudinary keys
cloudinary.cloud_name=dy1vcpqoj
cloudinary.api_key=332444278728165
cloudinary.api_secret=Z5Kqxq1ab_gd-6aRMMFT5XzfsWA